spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.output.ansi.enabled=always
spring.jpa.defer-datasource-initialization=true
spring.config.import=optional:file:.env[.properties]
# spring.jpa.show-sql=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-days=30
app.sendgrid.api-key=${SENDGRID_API_KEY}
app.sendgrid.from-email=${SENDGRID_FROM_EMAIL}
app.sendgrid.from-name=REDr
app.verification.base-url=http://localhost:8080/auth
app.verification.token-expiry-hours=24
